config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users, only: [:index, :edit, :show]
  end
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :tasks
  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings
  has_many :tasks, through: :labelings
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :labelings
  has_many :labels, through: :labelings
  validates :title, presence: true
  validates :detail, presence: true, length: {maximum: 255 }
  enum priority: [:high, :middle, :low]

  scope :search_tasks, ->(pr) {
    if pr[:word].present? && pr[:status].present?
      title_status_search(pr[:word], pr[:status])
    elsif pr[:word].present?
      title_search(pr[:word])
    elsif pr[:status].present?
      status_search(pr[:status])
    end
  }

  scope :title_status_search, ->(wd, st) {
    tasks = Task.where("title LIKE ?", "%#{wd}%")
    @tasks = tasks.where(status: st)
  }

  scope :title_search, ->(wd) {
    @tasks = Task.where("title LIKE ?", "%#{wd}%")
  }

  scope :status_search, ->(st) {
    @tasks = Task.where(status: st)
  }

  def slice_detail
    if detail.size <= 6
      detail
    else
      "#{detail.slice(0..5)}..."
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_update :ensure_admin, if: :edt?
  before_destroy :ensure_admin, if: :dst?
  has_many :tasks, dependent: :destroy
  has_secure_password

  private
  def edt?
    User.find(self.id).admin
    #下記の方法だと、更新しようとしている値を参照する
    # self.admin
  end
  def dst?
    self.admin
  end
  def ensure_admin
    if User.where(admin: true).size == 1
      errors.add(:base, "don't edit/destoy")
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user?
  before_action :set_user, only: [:edit, :show ]
  def index
    # @users = User.all
    @users = User.includes(:tasks).order(admin: 'DESC')
  end

  def edit
    @user.update(admin: true)
    redirect_to admin_users_path
  end

  def show
    @user.update(admin: false)
    if @user.errors.any?
      flash[:danger] = '管理者ユーザがいなくなってしまいます'
    end
    redirect_to admin_users_path
  end

  private
  def admin_user?
    unless logged_in?
        redirect_to new_session_path
    else
      if @current_user.admin != true
        flash[:danger] = 'アクセス権限がありません'
        redirect_to user_path(@current_user.id)
      end
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def asc_desc_sort(tasks)
    if params[:sort_expired] == "ASC"
      @tasks = tasks.order(deadline: 'ASC')
      @order = "DESC"
    else
      @tasks = tasks.order(deadline: 'DESC')
      @order = "ASC"
    end
  end
end


# sym = :priority
# Task.order(sym => 'ASC')

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    pr = params[:session]
    user = User.find_by(email: pr[:email])
    if user && user.authenticate(pr[:password])
      session[:user_id] = user.id
      flash[:notice] = "#{user.name}さん、お帰りなさい"
      redirect_to user_path(user.id)
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  PER = 6
  before_action :tasks_logged_in?
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :edit_task?, only: [:show, :edit, :update, :destroy]

  def index
    user_tasks = @current_user.tasks
    @order = "ASC"
    @tasks = user_tasks.order(created_at: 'DESC')
    if pr = params[:labeL_search]
      @tasks = Label.find(pr[:label_id]).tasks
    end
    # if params[:labeL_search]
    #   @tasks = Label.find(params[:labeL_search][:label_id]).tasks
    # end
    if params[:sort_expired]
      asc_desc_sort(user_tasks)
    elsif params[:sort_priority]
      @tasks = user_tasks.order(priority: 'ASC')
    elsif params[:search]
      @tasks = user_tasks.search_tasks(params[:search])
    end
    @tasks = @tasks.page(params[:page]).per(PER)
  end

  def show
  end

  def new
    @task = @current_user.tasks.new
  end

  def create
    @task = @current_user.tasks.new(task_params)
    if @task.save
      flash[:notice] = 'タスクを作成しました'
      redirect_to task_path(@task.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = 'タスクを削除しました'
    redirect_to tasks_path
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :detail, :deadline, :status, :priority, label_ids: [])
  end

  def tasks_logged_in?
    # current_user
    # redirect_to new_session_path unless @current_user
    redirect_to new_session_path unless logged_in?
  end

  def edit_task?
    # unless @current_user == @task.user
    #   unless @current_user.id == 7
    #     redirect_to user_path(@current_user)
    #   end
    # end
    if @current_user != @task.user && @current_user.admin != true
      redirect_to user_path(@current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :users_logged_in?, except: %i[new create]
  before_action :set_user, only: %i[edit update show destroy]
  before_action :edit_user?, only: %i[edit show]

  def new
    redirect_to user_path(@current_user.id) if logged_in? && @current_user.admin != true
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "#{@user.name}さん、はじめまして！"
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = "#{@user.name}さん、プロフィールを変更しました！"
      redirect_to user_path(@user.id)
    else
      render edit
    end
  end

  def show
    @tasks = @user.tasks
  end

  def destroy
    @user.destroy
    if @user.errors.any?
      flash[:danger] = '管理者ユーザがいなくなってしまいます'
    else
      flash[:notice] = 'ユーザを削除しました'
    end
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def users_logged_in?
    redirect_to new_session_path unless logged_in?
  end

  def edit_user?
    if @current_user != @user && @current_user.admin != true
      # redirect_to user_path(@current_user.id)
      redirect_to tasks_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<table>
  <tr>
    <th>ユーザ一覧</th>
    <th><%= link_to 'ユーザを作成する', new_user_path %></th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td class="px-2">
      <%= user.name %>
      <%= user.email %>
    </td>
    <td class="px-4">
    投稿数:<%= user.tasks.size %>
      <%= link_to '編集', edit_user_path(user.id) %>
      <%= link_to '詳細', user_path(user.id) %>
      <%= link_to '削除', user_path(user.id), method: :delete, id:"delete_#{user.id}" %>
    </td>
    <td class="px-4">
      admin: <%= user.admin %>
      <% if user.admin %>
        <%= link_to '権限を削除する', admin_user_path(user.id) %>
      <% else %>
        <%= link_to '権限を付与する', edit_admin_user_path(user.id) %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <h3 class="navbar-brand">Task_Management</h3>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'タスク登録', new_task_path, class: 'nav-link text-body'%>
        </li>
        <li class="nav-item">
          <%= link_to 'タスク一覧', tasks_path, class: 'nav-link text-body'%>
        </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', session_path(1),
            method: :delete, class: 'nav-link text-body'%>
          </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'ログイン', new_session_path, class: 'nav-link text-body' %>
        </li>
        <li class="nav-item">
          <%= link_to '新規登録', new_user_path, class: 'nav-link text-body' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EveryLeafApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main m-4">
      <% if flash[:notice] %>
        <h4 class="alert alert-info"><%= flash[:notice] %></h4>
      <% elsif flash[:danger] %>
      <h4 class="alert alert-danger"><%= flash[:danger] %></h4>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <div class="card mx-auto" style="width: 40rem; margin-top: 60px;">
    <div class="card-body">
      <h4 class="card-title">タスクを登録</h4>
      <% if @task.errors.any? %>
        <% @task.errors.full_messages.each do |msg| %>
          <p class="alert alert-danger"><%= msg %></p>
        <% end %>
      <% end %>
      <p class="card-text">
        <%= form.label :title %><br>
        <%= form.text_field :title, class:'ml-4' %>
      </p>
      <p class="card-text">
        <%= form.label :detail %><br>
        <%= form.text_field :detail, class:'ml-4' %>
      </p>
      <p class="card-text">
        <%= form.label :deadline %>
        <%= form.datetime_select :deadline, use_two_digit_numbers: true %>
      </p>
      <p class="card-text">
        <%= form.label :status %>
        <%= form.select :status, [['未着手', '未着手'], ['着手中', '着手中'], ['完了', '完了']]%>
      </p>
      <p class="card-text">
        <%= form.label :priority %>
        <%= form.select :priority, [['高', 'high'], ['中', 'middle'], ['低', 'low']]%>
      </p>
      <p class="card-text">
        <%= form.collection_check_boxes(:label_ids, Label.all, :id, :title) do |l| %>
          <%= l.label {l.check_box + l.text}%>
        <% end %>
      </p>
      <div class='card-text' style="text-align: center;">
        <%= form.submit class: 'btn btn-primary'%>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form'%>

app/views/tasks/index.html.erb
<h3 class='ml-4'><%= @current_user.name  %>のタスク一覧</h3>
<%= form_with(scope: :search, local: true, url: tasks_path, method: :get) do |form| %>
  <%= form.label :word, 'タスク名:', class:'ml-5' %>
  <%= form.text_field :word %>
  <%= form.label :status, 'ステータス:', class:'ml-5'%>
  <%= form.select :status, [['未着手', '未着手'], ['着手中', '着手中'], ['完了', '完了']],
  include_blank: '選択してください'%>
  <%= form.submit '検索する', class:'ml-3' %>
<% end %>

<%= form_for(:labeL_search, local: true, url: tasks_path, method: :get) do |form| %>
  <%= form.label :label_id, 'ラベル名:', class:'m-2 ml-5'%>
  <%= form.select :label_id,
  Label.all.collect {|l| [l.title, l.id]}, include_blank: true %>
  <%= form.submit 'ラベル名で検索', class:'ml-3'%>
<% end %>

<table class="table container my-3 mx-4">
  <thead>
    <tr>
      <th scope="col">タスク名</th>
      <th scope="col">詳しい内容</th>
      <th scope="col">
        <%= link_to '終了期限', tasks_path(sort_expired: @order) %>
      </th>
      <th scope="col">
        登録日時
      </th>
      <th scope="col">
        ステータス
      </th>
      <th scope="col">
        <%= link_to '優先順位', tasks_path(sort_priority: "true")%>
      </th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr class='task'>
      <th scope="row"><%= task.title %></th>
      <td><%= task.slice_detail %></td>
      <td><%= task.deadline.strftime("%Y-%m-%d-%H:%M") %></td>
      <td><%= task.created_at.strftime("%Y-%m-%d") %></td>
      <td><%= task.status %></td>
      <td>
        <%= t("activerecord.enum.task.priority.#{task.priority}")%>
      </td>
      <td>
        <%= link_to '詳細', task_path(task.id), class: 'btn btn-primary' %>
        <%= link_to '編集', edit_task_path(task.id), class: 'btn btn-success' %>
        <%= link_to '削除', task_path(task.id), method: :delete, class: 'btn btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tasks%>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="jumbotron mx-auto" style="width: 90%;  margin-top: 60px;">
  <p class="display-4"><%= @task.title %></p>
  <p class="lead"><%= @task.detail %></p>
  <hr class="my-4">
  <p>
    ステータス: <%= @task.status %>
  </p>
  <p>
    優先度: <%= t("activerecord.enum.task.priority.#{@task.priority}")%>
  </p>
  <p>作成日時: <%= @task.created_at.strftime("%c") %></p>
  <p>終了期限: <%= @task.deadline.strftime("%c") %></p>
  <hr class="my-4">
  <div class="labels">
    <p>付いているラベル</p>
    <% @task.labels.each do |l| %>
      <p class='ml-2 p-2 badge badge-warning'><%= l.title %></p>
    <% end %>
  </div>
  <hr class="my-4">
  <div>
    <%= link_to '詳細', task_path(@task.id) %>
    <%= link_to '編集', edit_task_path(@task.id) %>
    <%= link_to '削除', task_path(@task.id), method: :delete %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |user| %>
  <div>
    <%= user.label :name %>
    <%= user.text_field :name %>
  </div>
  <div>
    <%= user.label :email %>
    <%= user.text_field :email %>
  </div>
  <div>
    <%= user.label :password %>
    <%= user.text_field :password %>
  </div>
  <div>
    <%= user.label :password_confirmation %>
    <%= user.password_field :password_confirmation %>
  </div>
  <%= user.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'form'%>

app/views/users/show.html.erb
<h3 class='ml-4'><%= @current_user.name  %>のタスク一覧</h3>
<div class="profile m-4">
  名前: <%= @current_user.name %><br>
  メールアドレス: <%= @current_user.email %>
</div>
<table class="table container my-3 mx-4">
  <thead>
    <tr>
      <th scope="col">タスク名</th>
      <th scope="col">詳しい内容</th>
      <th scope="col">
        <%= link_to '終了期限', tasks_path(sort_expired: @order) %>
      </th>
      <th scope="col">
        登録日時
      </th>
      <th scope="col">
        ステータス
      </th>
      <th scope="col">
        <%= link_to '優先順位', tasks_path(sort_priority: "true")%>
      </th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr class='task'>
      <th scope="row"><%= task.title %></th>
      <td><%= task.slice_detail %></td>
      <td><%= task.deadline.strftime("%Y-%m-%d-%H:%M") %></td>
      <td><%= task.created_at.strftime("%Y-%m-%d") %></td>
      <td><%= task.status %></td>
      <td>
        <%= t("activerecord.enum.task.priority.#{task.priority}")%>
      </td>
      <td>
        <%= link_to '詳細', task_path(task.id), class: 'btn btn-primary' %>
        <%= link_to '編集', edit_task_path(task.id), class: 'btn btn-success' %>
        <%= link_to '削除', task_path(task.id), method: :delete, class: 'btn btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>